README.md
Minor edits. Looking forward to using source_gen.
=> README copyedits

lib/src/build.dart, lib/src/generate.dart, test/generate_test.dart
For https://github.com/dart-lang/source_gen/issues/56
=> Expose omitGenerateTimestamp and followLinks via build, generate methods.

CHANGELOG.md, lib/src/annotation.dart, lib/src/utils.dart, pubspec.yaml, tool/travis.sh
=> Upgrade to use a later version of analyzer

CHANGELOG.md, lib/generators/json_literal_generator.dart, lib/generators/json_serializable_generator.dart, lib/src/annotation.dart, lib/src/builder.dart, lib/src/generated_output.dart, lib/src/generator.dart, lib/src/generator_for_annotation.dart, lib/src/utils.dart, pubspec.yaml, test/annotation_test.dart, test/builder_test.dart, test/json_serializable_test.dart, test/src/comment_generator.dart, test/src/test_phases.dart
Also stop using most deprecated analyzer APIs
=> Support latest version of build, upgrade analyzer dev

CHANGELOG.md, pubspec.yaml, test/find_libraries_test.dart
Will have to look at newly deprecated `PackageUriResolver` eventually
=> Latest analyzer

lib/src/annotation.dart, test/json_serializable_integration_test.dart, test/src/comment_generator.dart, test/src/io.dart, test/test_all.dart, test/test_utils.dart
and deprecated pkg/test usage of Throws
=> Clean up of library names, mirror usage

.travis.yml, CHANGELOG.md, pubspec.yaml
There are no breaking changes as far as source_gen is concerned
=> Support package:build 0.8.x

analysis_options.yaml
This is already an error – no points for duplication
=> Remove superfluous error

lib/source_gen.dart, lib/src/builder.dart, lib/src/json_serializable/type_helper.dart, lib/src/utils.dart, test/analysis_utils.dart, test/builder_test.dart, test/ensure_build_test.dart, test/src/comment_generator.dart, test/test_files/annotated_classes.dart, test/test_files/annotated_classes_part.dart, tool/build.dart, tool/phases.dart, tool/watch.dart
Closes https://github.com/dart-lang/source_gen/issues/151.
=> Add and conform license headers.

CHANGELOG.md, lib/builder.dart
Closes https://github.com/dart-lang/source_gen/issues/152.
=> Deprecate builder.dart.

analysis_options.yaml, lib/generators/json_serializable_generator.dart, lib/src/annotation.dart, lib/src/builder.dart, lib/src/library.dart, lib/src/revive.dart, pubspec.yaml
Explicitly ignore the others - stop the bleeding
=> Stop using a couple of implementation imports

lib/src/builder.dart
Fixes #219
Reduces the public surface area. Where applicable shifted documentation
from fields to constructors on the public classes.
=> Make all fields of _Builder private

lib/src/builder.dart
=> Add option to specify additional output extensions

CHANGELOG.md
=> Add upgrade wiki link in changelog

CHANGELOG.md, lib/src/builder.dart, pubspec.yaml, test/builder_test.dart
closes https://github.com/dart-lang/source_gen/issues/251
=> Log input id not library

CHANGELOG.md, lib/src/constants.dart, test/constants_test.dart
Closes https://github.com/dart-lang/source_gen/issues/256.
=> Add ConstantReader#isAny.

CHANGELOG.md, lib/src/type_checker.dart, test/type_checker_test.dart
Closes https://github.com/dart-lang/source_gen/issues/257.
=> Add TypeChecker#hasAnnotationOf{Exact}.

CHANGELOG.md, lib/source_gen.dart, lib/src/generator_for_annotation.dart, lib/src/library.dart
=> Add library methods

lib/src/builder.dart
Closes https://github.com/dart-lang/source_gen/issues/288.
=> Doc update.

lib/src/constants/revive.dart
Work towards https://github.com/dart-lang/source_gen/issues/290.
=> Update docs for reviveInstance.

CHANGELOG.md, lib/src/library.dart
Closes https://github.com/dart-lang/source_gen/issues/293.
I could add additional test cases... but I'm not sure it really helps anything here.
=> Add more pathToX functions.

CHANGELOG.md, lib/source_gen.dart, lib/src/utils.dart, test/utils_test.dart
Closes https://github.com/dart-lang/source_gen/issues/294.
=> Add typeNameOf(DartType).

.travis.yml, CHANGELOG.md, pubspec.yaml
We should publish as well so I removed the -dev from the version.
=> allow build version 0.12.0

.travis.yml
https://github.com/dart-lang/sdk/issues/31940 is fixed
=> Unpinned dev SDK in travis config

CHANGELOG.md, lib/src/constants/revive.dart, pubspec.yaml, test/constants_test.dart
... before, all top-level and static-fields weren't resolved correctly.
Closes https://github.com/dart-lang/source_gen/issues/290.
=> Bug fix for Revivable, and prepare to release.

lib/src/builder.dart, lib/src/generator.dart, test/builder_test.dart
=> Code cleanup

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/lib/src/generated_output.dart, source_gen/test/builder_test.dart, source_gen/test/src/comment_generator.dart
This builds on #336 and #337 
Happy to wait for those – or land them all together.
Every commit is nicely isolated and commented. Figured this would be more efficient than 6 separate PRs
=> A lot of cleanup

source_gen/lib/source_gen.dart, source_gen/test/builder_test.dart, source_gen/test/src/unformatted_code_generator.dart
=> explicit shows for exported members, test cleanup

source_gen/build.yaml, source_gen/lib/builder.dart
work towards https://github.com/dart-lang/source_gen/issues/319
=> feature: add build.yaml setup for CombiningBuilder

source_gen/lib/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
=> Update pkg:test, fixes for source_gen

source_gen/lib/builder.dart, source_gen/test/builder_test.dart
Includes the name of the source parts in a comment before its content
Nice when debugging
=> feature(CombiningBuilder): add optional `includePartName` param

source_gen/lib/builder.dart
`AssetId` implements `Complarable<AssetId>`
=> Drop custom comparison function

.travis.yml, source_gen/CHANGELOG.md, source_gen/lib/src/output_helpers.dart, source_gen/pubspec.yaml, source_gen/test/library/find_type_test.dart, source_gen/test/type_checker_test.dart
Since 0.9.0 is blocked by `pkg:build_` issues...
=> Prepare a 0.8.3 release

source_gen/.mono_repo.yml, source_gen/lib/src/generator_for_annotation.dart, source_gen/lib/src/output_helpers.dart, source_gen/test/output_helpers_test.dart, tool/travis.sh
And the associated test change
=> misc: cherry-pick part of 8f37134fd7 that simplifies output_helpers

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml
So we have a consistent CHANGELOG
=> Merge 0_8_x branch

source_gen/CHANGELOG.md, source_gen/lib/src/span_for_element.dart, source_gen/pubspec.yaml, source_gen/test/span_for_element_test.dart
Fixes https://github.com/dart-lang/source_gen/issues/379
=> Correctly handle properties in spanForElement, prepare for release

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
Unblocks https://github.com/dart-lang/json_serializable/issues/339
=> Support the latest package:analyzer, prepare for release

.travis.yml, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, tool/travis.sh
I noticed the tests were running pretty slow, this definitely helps some:
$  time pub run test
00:42 +204: All tests passed!                                                                                                                                                                                     
real	0m42.905s
user	1m19.300s
sys	0m3.039s
$ time pub run build_runner test
[INFO] Generating build script completed, took 299ms
[INFO] Creating build script snapshot... completed, took 11.0s
[INFO] Building new asset graph completed, took 889ms
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[INFO] Running build completed, took 24.6s
[INFO] Caching finalized dependency graph completed, took 65ms
[INFO] Creating merged output dir `/tmp/build_runner_testHYXWTX/` …
=> use build_vm_compilers for running tests

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
=> dont create invalid parts, and allow analyzer 0.34.x

source_gen/test/builder_test.dart, source_gen/test/span_for_element_test.dart
We hardcode expected output in the tests and it was changed in
https://github.com/dart-lang/source_span/pull/25
=> Update test expectations for source span output

.travis.yml, _test_annotations/mono_pkg.yaml, example/mono_pkg.yaml, example_usage/mono_pkg.yaml, mono_repo.yaml, source_gen/lib/src/builder.dart, source_gen/mono_pkg.yaml, tool/travis.sh
=> fix dartfmt for latest dev SDK

example_usage/README.md
Small change in the example_usage README to clarify how to run the example.
=> Updated README with how to run the example_usage

source_gen/README.md
Added links to `example` and `example_usage` in the main README.
=> Update main README with ref to examples

.travis.yml, source_gen/lib/src/constants/revive.dart, source_gen/pubspec.yaml
See https://github.com/dart-lang/sdk/issues/38546#issuecomment-534671075 for the context.
=> Get element of DartObject using also toFunctionValue().

.travis.yml, _test_annotations/mono_pkg.yaml, example/mono_pkg.yaml, example_usage/mono_pkg.yaml, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/type_checker_test.dart, tool/travis.sh
`ClassElement.type` is deprecated, use `ClassElement.isntantiate()`
instead.
Bump minimum analyzer to `0.39.0`.
=> Migrate off of deprecated analyzer APIs

analysis_options.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/lib/src/generator_for_annotation.dart, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/src/comment_generator.dart
Remove errors section from analysis_options
=> Add and fix missing pedantic lints

source_gen/CHANGELOG.md, source_gen/lib/src/generator_for_annotation.dart
=> Clarify that only top-level elements are targeted

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/lib/src/generated_output.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/generator_for_annotation_test.dart
There should be no user-visible behavior change.
=> Streamlined error handling in all builders

source_gen/README.md
=> chore(typo in readme)

.travis.yml, _test_annotations/mono_pkg.yaml, _test_annotations/pubspec.yaml, example/mono_pkg.yaml, example/pubspec.yaml, example_usage/mono_pkg.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml
Bump minimum build_test version
Update all other packages
=> Update minimum SDK version to 2.7.0

source_gen/CHANGELOG.md, source_gen/lib/src/library.dart
=> Including extensions on allElements

source_gen/CHANGELOG.md, source_gen/lib/src/constants/reader.dart, source_gen/test/constants_test.dart
Added two new members, updated two existing members
=> Add support for Set to ConstantReader

.travis.yml, _test_annotations/mono_pkg.yaml, _test_annotations/pubspec.yaml, example/mono_pkg.yaml, example/pubspec.yaml, example_usage/mono_pkg.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, tool/travis.sh
=> Add support for allowSyntaxErrors flag

.travis.yml, source_gen/CHANGELOG.md, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, tool/travis.sh
pbr test is causing failures on 2.12.0-dev
Also sort imports
=> Move to use `pub run test` directly

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/src/comment_generator.dart
Fixes https://github.com/dart-lang/source_gen/issues/497
=> fix bug in early bailout case - check part files for annotations also

source_gen/lib/src/builder.dart
This is necessary for https://dart-review.googlesource.com/c/sdk/+/176720
=> Use parsed AST to check if the generated part is the expected one.

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
I recommend publishing this to break circular dependency problems with glob.
=> Expand glob range on source_gen

example/pubspec.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/pubspec.yaml
=> Prepare 0.9.10+4 release

source_gen/lib/src/type_checker.dart, source_gen/test/type_checker_test.dart
Handle a valid null case without crashing
Provide a detailed error message trying to track down https://github.com/dart-lang/sdk/issues/45127
=> Improve error handling in UnresolvedAnnotationException

analysis_options.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
Related to https://github.com/dart-lang/source_gen/issues/490
=> Clear warning message

analysis_options.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/type_checker_test.dart
Fixes https://github.com/dart-lang/source_gen/issues/534
=> fix TypeChecker.runtimeType for types that come from non-package: uris

.github/workflows/dart.yml, _test_annotations/mono_pkg.yaml, example/mono_pkg.yaml, example_usage/mono_pkg.yaml, source_gen/mono_pkg.yaml, tool/ci.sh
Drop superfluous --fatal-warnings with analyzer
=> Update to the latest mono_repo

source_gen/lib/src/utils.dart
To re-apply https://dart-review.googlesource.com/c/sdk/+/205140
=> ignore:unnecessary_non_null_assertion for future non-nullable LibraryElement.name

source_gen/CHANGELOG.md, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/src/comment_generator.dart
Fixes https://github.com/dart-lang/source_gen/issues/543
=> fix analyzer warnings, require analyzer 2.x

.github/workflows/dart.yml, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/span_for_element_test.dart, tool/ci.sh
This is expected to fail today, ~I propose landing it red, and it should go green with https://github.com/dart-lang/source_gen/pull/571.~ skipping failing tests and linked issues.
=> Add windows testing

.github/workflows/dart.yml, _test_annotations/mono_pkg.yaml, example/mono_pkg.yaml, example_usage/lib/library_source.dart, example_usage/mono_pkg.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/generator.dart, source_gen/lib/src/type_checker.dart, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/type_checker_test.dart, tool/ci.sh
See https://github.com/google/json_serializable.dart/issues/1081 for details. This will need to be based against a branch off of the latest v0.9 tag.
@kevmoo
=> [Backpatch v0.9] Widen dart_style range

source_gen/CHANGELOG.md, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
Tested locally with a dependency override.
=> Allow the latest analyzer

source_gen/test/builder_test.dart
Fixes https://github.com/dart-lang/source_gen/issues/605
=> Bump min SDK used in language version test to 2.12

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
- update the pubspec 'repository' field
=> update the pubspec 'repository' field

source_gen/CHANGELOG.md, source_gen/lib/src/type_checker.dart, source_gen/pubspec.yaml, source_gen/test/type_checker_test.dart
Related to https://github.com/dart-lang/source_gen/issues/638
=> add test for enum assignability

.github/workflows/dart.yml, analysis_options.yaml, example_usage/test/ensure_build_test.dart, source_gen/CHANGELOG.md, source_gen/lib/source_gen.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/constants/reader.dart, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/generator_for_annotation_test.dart, source_gen/test/test_files/annotated_classes.dart, source_gen/test/test_files/annotated_classes_part.dart, source_gen/test/type_checker_test.dart, source_gen/test/utils_test.dart
Fixes https://github.com/dart-lang/source_gen/issues/638
=> Enable and fix lints, fix changelog, prepare v1.2.7

.github/workflows/no-response.yml, .github/workflows/publish.yaml, _test_annotations/pubspec.yaml, example/pubspec.yaml, example_usage/pubspec.yaml, source_gen/README.md
=> blast_repo fixes

source_gen/lib/builder.dart, source_gen/lib/src/builder.dart, source_gen/test/builder_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/generator_for_annotation_test.dart, source_gen/test/test_files/annotations.dart, source_gen/test/type_checker_test.dart, source_gen/test/utils_test.dart
These were not surfaced in the stable Dart SDK, but they start getting
reported in the dev release. Apply fixes with `dart fix`.
=> Add missing trailing commas

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
=> Prepare to publish

source_gen/lib/src/library.dart
=> Ignore some deprecated analyzer members

example/pubspec.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml
Update min versions of a number of packages
=> Fix deprecation in analyzer API

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
=> Allow analyzer 8.
