lib/src/annotation.dart, test/annotation_test.dart, test/test_files/annotated_classes.dart, test/test_files/annotated_classes_part.dart, test/test_files/annotations.dart
Annotations defined in parts of libraries are not matched by generators, which is unexpected behavior. (Annotations shouldn't always have to be defined in a main library file.)
* Match annotations based on equality between owner library URI and source _library_ uri, as opposed to owner library uri and source _file_ URI.
* Update tests.
=> Match annotations defined in parts, add relevant unit tests

lib/generators/json_serializable_generator.dart
If a list type is null, the call to map() is prevented, but toList() is still called resulting in a NPE.
=> Add null aware operator before calling toList.

lib/src/generated_output.dart
Currently lines after the second one are concatenated without newlines, leading to error output like:
// Error: first line of error message.
//        Second line of error message. //        Third line of error message.        // Fourth line of error message.
=> Fix multiline error output for more than two lines of error message.

lib/src/annotation.dart
Instead of throwing a NPE, throw an ArgumentError with a message to suggest that a dependency might be missing.
=> Fix NPE when ElementAnnotation.constantValue returns null.

CHANGELOG.md, lib/src/annotation.dart, pubspec.yaml
This makes annotation.dart forward compatible with implementations of the Resolvers and LibraryElement using analyzer summary files.
=> avoid computeNode calls

CHANGELOG.md, lib/src/annotation.dart, pubspec.yaml
Fixes https://github.com/dart-lang/source_gen/issues/100
=> Use library URI (not name) to look up annotation

CHANGELOG.md, lib/generators/json_serializable_generator.dart
The `interfaces` getter does not behave as expected. See
https://github.com/dart-lang/sdk/issues/27947
This code was safe before since List happened to explicitly have
`implements Iterable`, but now that there is an
`EfficientLengthIterable` interface in between it isn't working.
Recursively check interfaces the same way we recursively check the
superclass. This now ignores the edge case where multiple interfaces
matched the tester and will return the first match.
=> Fix check for implemented interfaces

lib/src/utils.dart, pubspec.yaml
The getters in the analyzer's AST data structures will soon be changed to less specific types, so we need to use the new interface in order to avoid warnings.
=> Make use of analyzer's new resolutionMap interface.

lib/src/annotation.dart
Extract matchTypes from matchAnnotation so that it can be used in cases where the type comes from a different source (like a DartObject instance).
=> Extract matchTypes from matchAnnotation.

CHANGELOG.md, lib/src/builder.dart, pubspec.yaml
If we can't get a LibraryElement for a primary input it should not have
any output. Return early rather than throw later.
=> Smooth degradataion for non-library assets

lib/src/builder.dart
Some places use the toString for debugging and knowing which generators
are involved is useful.
=> Add toString() to GeneratorBuilder

lib/src/builder.dart
Closes https://github.com/dart-lang/source_gen/issues/130.
I validated internally this produces a nicer error message, such as:
```
[SEVERE]: Error formatting the generated source code for <REDACTED>|lib/focus_trap.dart which was output to lib/focus_trap.template.dart.
This may indicate an issue in the generated code or in the formatter.
Please check the generated code and file an issue on source_gen if appropriate.
Could not format because the source could not be parsed:
<REDACTED>
```
=> Add more context about dartfmt failures

CHANGELOG.md, lib/src/builder.dart, pubspec.yaml
Use concatenated `''` rather than `'''` so that we can break lines
separately in the source from where we want them broken in the output
=> Reflow and format help message

.travis.yml, CHANGELOG.md, lib/src/builder.dart, lib/src/utils.dart, pubspec.yaml
The AnalysisException thrown during initial iterating over elements can
be very noisy. Stack traces are included in the `toString()` and it's
detail that most users won't care about.
- Add a safeIterate utility method which allows catching the exceptions
specifically thrown by the elements iterable and not by the Builder
- Simplify to a message about failing to resolve the input. Include the
extra details in a log.fine
=> Less verbose error for analysis error

.travis.yml, CHANGELOG.md, lib/src/builder.dart, pubspec.yaml
- Replace declareOutputs with buildExtensions
- Upgrade build related dependencies
=> Upgrade to build 0.9.0

test/analysis_utils.dart
The call to `JavaSystemIO.setProperty` is a noop – see https://codereview.chromium.org/2916303003/
Using `.` in `getResource` just happened to work, but this code path is broken in other contexts where the target package is not in the current directory.
=> Fix potential issues with project

README.md, lib/src/builder.dart, lib/src/generator.dart, lib/src/generator_for_annotation.dart, pubspec.yaml
Specifically, clarifying the _role_ of this package (since it forked into `build`), what this package _does_ and (does not do), and added API documentation to the most common classes that were sorely lacking.
I also added a gitter chatroom, since there seems to be enough users trying this out to warrant. We can probably re-use this chatroom for the various build packages.
Closes https://github.com/dart-lang/source_gen/issues/135.
=> Incremental enhancements to README and dartdoc

CHANGELOG.md, lib/generators/json_serializable_generator.dart, lib/source_gen.dart, lib/src/type_checker.dart, test/type_checker_test.dart
This will be nice to have versus stuffed into the AngularDart compiler, and it doesn't feel "right" going into a library like `build`, which I think benefits from having a very small interface and low-threshold for changes.
Advantages of this approach
* Adds an "approved" (not `/lib/src/annotations.dart') way of performing checks.
* Has two backing implementations not based on `dart:mirrors` (for long-term safety).
* Easy re-usable setup for complex compilers like `inject` or `angular`.
See `type_checker_test.dart` for some functional tests.
Closes https://github.com/dart-lang/source_gen/issues/136.
=> Add TypeChecker class.

lib/generators/json_serializable_generator.dart, lib/src/json_serializable/type_helper.dart, lib/src/type_checker.dart, test/type_checker_test.dart
Building off https://github.com/dart-lang/source_gen/pull/153
=> Added `isAssignableFrom(Type)` to TypeChecker

CHANGELOG.md, lib/src/builder.dart, lib/src/utils.dart, test/builder_test.dart
Closes https://github.com/dart-lang/source_gen/issues/101.
=> Add helpers and checks for partial names.

CHANGELOG.md, lib/source_gen.dart, lib/src/find_type.dart, lib/src/type_checker.dart, test/find_type_test.dart, test/type_checker_test.dart
Closes https://github.com/dart-lang/source_gen/issues/160.
Also added test cases, which in turn found a bug. Whad'ya know @jakemac53 🐑 
Closes https://github.com/dart-lang/source_gen/issues/161.
=> Add findType, and fix a bug in TypeChecker.

CHANGELOG.md, lib/source_gen.dart, lib/src/constants.dart, test/constants_test.dart
Partial progress towards https://github.com/dart-lang/source_gen/issues/169.
`List`, `Map`, and other types are a little trickier, so hoping to get some incremental work first.
=> Add a Constant helper class.

CHANGELOG.md, lib/src/builder.dart, lib/src/utils.dart, test/builder_test.dart
Closes https://github.com/dart-lang/source_gen/issues/157.
Closes https://github.com/dart-lang/source_gen/pull/138.
This approach will not lock-in all future users of `source_gen` to an unreleased `1.25.0`. We can flip the default value in a future (breaking) release.
/cc @davidmorgan
=> GeneratorBuilder flag for "part of" without "library".

lib/src/constants.dart, test/constants_test.dart
Closes https://github.com/dart-lang/source_gen/issues/177.
@jakemac53 is OOO, @alorenzen would you mind taking a look too?
=> Added instanceOf to ConstantReader.

lib/source_gen.dart, lib/src/constants.dart, lib/src/revive.dart, lib/src/type_checker.dart, lib/src/utils.dart, test/constants_test.dart
Partial support of https://github.com/dart-lang/source_gen/issues/178.
Still missing as of this PR:
* Any sort of sugar for `enum`, though it should work out of the box anyway.
* Error recovery: We just return `null` when something is not resolvable, ideally I'd like to either throw or return a specialized instance (`Unrevivable`) that explains why not (usually due to a private constructor, or not being able to trace how the object was created
Good starting point though I think.
=> Constants reviver

CHANGELOG.md, pubspec.yaml
`lib/src/revive.dart` line 26 makes a call to DartObjectImpl#getInvocation() which requires [analyzer 0.29.10](https://github.com/dart-lang/sdk/blob/analyzer-0.29/pkg/analyzer/CHANGELOG.md#02910).
=> increase analyzer min version

CHANGELOG.md, lib/src/type_checker.dart, pubspec.yaml, test/type_checker_test.dart
Closes https://github.com/dart-lang/source_gen/issues/199.
This is a *breaking change*, and has been reflected on the CHANGELOG+pubspec. In reality it should affect a very small number of users, but I would like to get this in so it's used in Angular ASAP (we support inheriting from `@Component` right by accident, we don't want that).
=> Add annotationsOfExact.

CHANGELOG.md, lib/src/type_checker.dart, pubspec.yaml, test/type_checker_test.dart
Branched from https://github.com/dart-lang/source_gen/pull/200.
Closes https://github.com/dart-lang/source_gen/issues/198.
=> Nicer failures when an annotation is not resolvable

CHANGELOG.md, lib/src/type_checker.dart, pubspec.yaml, test/type_checker_test.dart
Branched from https://github.com/dart-lang/source_gen/pull/201.
Closes https://github.com/dart-lang/source_gen/issues/196.
=> Add TypeChecker.any

test/builder_test.dart
Closes https://github.com/dart-lang/source_gen/issues/192.
=> Add a test for no outputs.

test/type_checker_test.dart
Closes https://github.com/dart-lang/source_gen/issues/204.
=> Add tests for annotation matching.

CHANGELOG.md, lib/source_gen.dart, lib/src/span_for_element.dart, lib/src/utils.dart, pubspec.yaml, test/span_for_element_test.dart
Closes https://github.com/dart-lang/source_gen/issues/203.
I had to get a little creative for environments where the exact source information is not provided as part of the element structure (i.e. Bazel + Summaries I think), so I don't mind annotating this `@experimental` and doing more validation before we settle on this implementation.
/cc @natebosch too, since I think @jakemac53 is out for a bit.
=> Add `spanForElement`, for nicer debugging messages.

CHANGELOG.md, lib/src/builder.dart, lib/src/utils.dart, test/builder_test.dart, test/span_for_element_test.dart
Closes https://github.com/dart-lang/source_gen/issues/7.
I tested the positive and negative cases on the existing `builder_test` cases, and there were some failures (probably when `.g.dart` wasn't the norm yet), so I updated those test cases. Now they will fail if anything is logged to the console, and added a test that checks something _is_ logged when the `part` definition is missing.
I wanted to do `severe`, but we should validate internally first me thinks.
=> Add a warning when 'part' is missing.

CHANGELOG.md, pubspec.yaml
Currently it's possible to resolve to a version that won't work because
it's missing the `SourceFile.fromString()` constructor.
=> Tighten constraint on source_span

lib/src/builder.dart, lib/src/utils.dart
This existed so that we could separate the exceptions that occur during
iteration from the exceptions that occur during processing since a for
loop can't have a try/catch around only getting elemetns. This is more
easily expressed with a try/catch around `Iterable.toList()`.
=> Drop the safeIterate helper

CHANGELOG.md, lib/source_gen.dart, lib/src/builder.dart, lib/src/utils.dart
This is a necessary utility as we change `Generator` to take a
`LibraryElement` in #223
=> Rename and expose allElements

CHANGELOG.md, README.md, lib/src/builder.dart, test/builder_test.dart
Closes #117
Fixes the API weirdness where `isStandalone` only works with a single
Generator, and shouldn't be passed with `requireLibraryDirective`.
This is a small step - we still need to clean up the interface (#219).
- Make `GeneratorBuilder` private as `_Builder`.
- Subclass as `PartBuilder` and `LibraryBuilder` with only forwarding
constructors to give nicer signatures.
=> Add separate classes for Part vs Library builders

CHANGELOG.md, lib/src/builder.dart
Towards #219
Cannot yet use new Function syntax - it causes the released version of
`package:analyzer` to crash.
=> Make OutputFormatter typedef private

CHANGELOG.md, lib/source_gen.dart, lib/src/generator_for_annotation.dart, lib/src/library.dart, lib/src/utils.dart, test/src/comment_generator.dart
Fixes #229
LibraryReader is a nicer place for this utility and will give us a
surface to attach more functionality than scattering top-level methods.
=> Move allElements to LibraryReader

pubspec.yaml
- package:collection is only used under test/ so move it to
dev_dependencies.
- Drop dev_dependencies on no-longer used package build_runner and
mockito.
=> Prune dependencies

CHANGELOG.md, lib/src/builder.dart, lib/src/generator.dart, lib/src/generator_for_annotation.dart, lib/src/library.dart, test/builder_test.dart, test/src/comment_generator.dart, test/src/unformatted_code_generator.dart
Similar to ConstantReader this will make it easier to use new utility
methods as we add them.
- Make `_element` public so that clients can still access the
`LibraryElement` when needed.
- Change the `generate` method signature and all implementations.
- Wrap the argument in `builder.dart`.
=> Generate with LibraryReader over LibraryElement

README.md
- Drop references to deleted `tool/` directory.
- Elaborate on how `source_gen` fits into `build`.
=> Some READEME cleanup

lib/src/constants.dart
=> Document throwing behavior of ConstantReader.read

CHANGELOG.md, lib/src/constants.dart, test/constants_test.dart
Closes https://github.com/dart-lang/source_gen/issues/214.
=> Add ConstantReader.peek.

CHANGELOG.md, lib/src/constants.dart, test/constants_test.dart
Closes https://github.com/dart-lang/source_gen/issues/216.
=> Add ConstantValue.objectValue.

lib/src/library.dart
Fixes #245
The library is available through `element` and most Generators will want
to make a distinction anyway.
=> Don't emit library in allElements

CHANGELOG.md, lib/src/type_checker.dart, test/type_checker_test.dart
Closes https://github.com/dart-lang/source_gen/issues/248
=> add `throwOnUnresolved` to TypeChecker methods to allow matching annotations in a non-fully resolved context

CHANGELOG.md, lib/src/generator.dart, lib/src/generator_for_annotation.dart, pubspec.yaml
closes https://github.com/dart-lang/source_gen/issues/250
=> Support FutureOr<String> for Generator{ForAnnotation}

CHANGELOG.md, pubspec.yaml, test/builder_test.dart
Update to `build_test` v 0.9.0 and update tests to use `decodedMatches`
=> Support latest package:build

analysis_options.yaml, lib/src/builder.dart, lib/src/constants/revive.dart, lib/src/constants/utils.dart, lib/src/generated_output.dart, lib/src/type_checker.dart, lib/src/utils.dart, test/src/io.dart
Split lints into 'error's and 'style' and sort within each section. Fix
a few existing violations.
=> Add additional lints

CHANGELOG.md, lib/src/generator_for_annotation.dart, pubspec.yaml, test/generator_for_annotation_test.dart
Fixes #285
Previously if the library had any matching annotations we would always
output something - either the String "null" or empty lines.
Skip outputs that are null or empty. Add a regression test.
=> Handle empty outputs in GenerateForAnntation

CHANGELOG.md, lib/src/library.dart, test/library/path_to_url_test.dart
Partial work towards https://github.com/dart-lang/source_gen/issues/293.
I omitted `pathToAsset` and `pathToElement`, because (a) they are just conveniences and (b) this is the bulk of the code for first review - the latter should be quite quick.
=> Add LibraryReader.pathToUrl.

lib/src/library.dart, test/library/prefix_for_type_test.dart, test/library_reader_test.dart
Work towards https://github.com/dart-lang/source_gen/issues/292.
I've made the feature package-private so we can iterate. It's possible we won't even be able to launch this as-is (if `computeNode()` explodes), but at least we will have the test case(s) when we have a replacement API, so I think it's worth checking (most) of this in.
=> Start adding LibraryReader.prefixForType.

CHANGELOG.md, lib/src/library.dart, pubspec.yaml
The pathToUrl function in LibraryReader returns an empty Url when the url is an asset on Windows.
This PR aims to fix this issue.
=> Make pathToUrl working on Windows

lib/src/constants/utils.dart
I was using `@visibleForTesting` improperly.
=> Delint analysis issues.

.travis.yml, CHANGELOG.md, lib/source_gen.dart, lib/src/type_checker.dart, pubspec.yaml, test/type_checker_test.dart
Closes https://github.com/dart-lang/source_gen/issues/316.
Also prepares for a quick release so I can use it in AngularDart.
/cc @MichaelRFairhurst who is aware of the `.annotationAst` usage.
=> Add better errors to TypeChecker.

CHANGELOG.md, lib/src/constants/revive.dart, pubspec.yaml, test/constants_test.dart, test/test_files/annotations.dart
Closes #320.
... and prepare for release, because we need this internally ASAP.
=> fix: Support reviving a reference to a function.

source_gen/test/generator_for_annotation_test.dart
The first test takes 30s+ longer on Travis
Also consolidated the skip output tests - and added a couple more
=> fix(test): 3x timeout on generator_for_annotation_test

source_gen/lib/src/builder.dart, source_gen/test/builder_test.dart
=> Fixes for CombiningBuilder

source_gen/lib/src/builder.dart
It's nice when you want to ship more than one generator in a package
For example: json_serializable, json_serializable-literal
=> fix(SharedPartBuilder) allow `-` in part Id

source_gen/CHANGELOG.md, source_gen/lib/src/generator_for_annotation.dart, source_gen/test/generator_for_annotation_test.dart
Partial revert of 8f37134fd7a8d983778d79cbdbd313f40df1c7f6
While migrating usages it became apparent that repeatedly needing to
dereference `annotatedElement` is annoying.
=> Reseparate args to generateForAnnotatedElement

source_gen/build.yaml, source_gen/lib/builder.dart, source_gen/pubspec.yaml
Towards #319
These never need to be served or included in the merged output directory
so they should always be cleaned by the post process builder.
=> Add cleanup of .g.part files

source_gen/README.md
Towards #319
Describes how to use SharedPartBuilder to write to .g.dart files,
including how to configure the `build.yaml`.
Remove references to Transformers.
=> Update README for SharedPartBuilder

_test_annotations/pubspec.yaml
Dart 2 treats packages without an SDK constraint as <2.0.0
=> misc: add SDK constraint to _test_annotation package

source_gen/README.md
Hello,
I found an error in the `build.yaml` configuration example in the README. Here's a quick fix
=> Fix readme typo

source_gen/CHANGELOG.md, source_gen/lib/src/library.dart, source_gen/pubspec.yaml, source_gen/test/library/find_type_test.dart
Also prepare to release 0.9.0+1
=> fix(LibraryReader) `classes` should return all classes, including parts

.travis.yml, analysis_options.yaml, source_gen/.mono_repo.yml, source_gen/lib/builder.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/constants/reader.dart, source_gen/lib/src/constants/revive.dart, source_gen/lib/src/constants/utils.dart, source_gen/lib/src/generated_output.dart, source_gen/lib/src/generator.dart, source_gen/lib/src/generator_for_annotation.dart, source_gen/lib/src/library.dart, source_gen/lib/src/output_helpers.dart, source_gen/lib/src/span_for_element.dart, source_gen/lib/src/type_checker.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/constants_test.dart, source_gen/test/generator_for_annotation_test.dart, source_gen/test/library/find_type_test.dart, source_gen/test/library/path_to_url_test.dart, source_gen/test/output_helpers_test.dart, source_gen/test/span_for_element_test.dart, source_gen/test/src/comment_generator.dart, source_gen/test/test_files/annotated_classes.dart, source_gen/test/test_files/annotated_classes_part.dart, source_gen/test/test_files/annotations.dart, source_gen/test/type_checker_test.dart
- Set minimum SDK to one that is Dart 2 by default.
- Run dartfmt --fix
- Test on stable on Travis.
=> Run dartfmt --fix to drop optional new

source_gen/CHANGELOG.md, source_gen/lib/src/constants/revive.dart, source_gen/pubspec.yaml, source_gen/test/constants_test.dart
Closes https://github.com/dart-lang/source_gen/issues/374.
... also prepare to release.
=> ConstantReader.revive implementation now matches the documentation

source_gen/pubspec.yaml, source_gen/test/constants_test.dart
The new method on Map directly is nicer.
Also clean up trailing whitespace.
=> Stop using mapMap from package:collection

source_gen/CHANGELOG.md, source_gen/lib/src/library.dart, source_gen/pubspec.yaml
- Use `LibraryElement.exportNamespace` to find types across a libraries
entire visible surface area rather than referencing a
`NamespaceBuilder`.
- Use the different getters for element typs from
`CompilationUnitElement` to get all members of a library rather than
getting the declarations from a `CompilationUnit`.
- Increase minimum anlayzer version to ensure that the `mixins` getter
is available.
=> Remove some analyzer ast and src imports

source_gen/CHANGELOG.md, source_gen/lib/src/library.dart, source_gen/pubspec.yaml, source_gen/test/library/find_type_test.dart
Fixes #388
Deprecate the `classElements` getter since it is ambiguous, both classes
and enums are represented by `ClassElement` in analyzer, but we don't
want to exclusively always mix them in this interface. Add the name
`classes` to be more specific. Add an implementation for `enums.`
=> Add LibraryReader.enums

source_gen/CHANGELOG.md, source_gen/lib/src/type_checker.dart, source_gen/pubspec.yaml
The old code path does not work when the ElementAnnotation was returned
by an `AnalysisDriver` instead `AnalysisContext`. Prepare for
`build_resolvers` to switch to `AnalysisDriver` by migrating to a
forwards compatible approach.
=> Use ParsedLibraryImpl to find source span

source_gen/lib/src/builder.dart, source_gen/pubspec.yaml
closes #385
Make it more clear how the behavior of PartBuilder, SharedPartBuilder,
and LibraryBuilder differ from eachother.
=> Expand doc comments for *Builder classes

.travis.yml, example/mono_pkg.yaml, example/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/lib/src/type_checker.dart, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, tool/travis.sh
This was a transition API until we could know that `element.session`
would be available. With analyzer above version `0.35.0` we know that
`build_resolvers` will be using a code path that makes `.session`
available.
Also:
- Remove unnecessarily low minimum dependency versions for packages that
we would not be able to solve with due to the analyzer constraint.
- Replace an `// ignore: unawaited_futures` with `unawaited` call from
`package:pedantic`.
- Remove comment referencing closed SDK issue. GOing through the
`AnnotatedNode` is the correct approach for finding source ranges.
- Rename method to avoid a prefix of `get`.
=> Migrate off ParsedLibraryResultImpl

source_gen/README.md
in all places where this is displayed, it's already pretty obvious
=> Remove redundant header from readme

.travis.yml, _test_annotations/mono_pkg.yaml, source_gen/CHANGELOG.md, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, tool/travis.sh
- Add a changelog and bump version number.
- Update min SDK so that we can test on Travis with our lower bound.
- Re-run mono_repo after manual edits.
=> Prepare to publish with analyzer fix

source_gen/test/generator_for_annotation_test.dart, source_gen/test/type_checker_test.dart
We would like to change `DartType.toString()` to include nullability suffixes.
It is not used much in this package, but it is still used in string comparisons and changes to `analyzer` will break these tests.
=> Don't use DartType.toString()

source_gen/CHANGELOG.md, source_gen/lib/src/generator.dart, source_gen/pubspec.yaml
If analysis is being done using a combination of srcs + summaries, and the element specified is in a summary, then we won't be able to find the src to log it.
Currently this causes an uncaught exception :)
A simple try/catch improves matters.
=> Log more carefully.

example_usage/build.yaml, example_usage/lib/library_source.g.dart, source_gen/CHANGELOG.md, source_gen/README.md, source_gen/lib/builder.dart, source_gen/test/builder_test.dart
Related to https://github.com/dart-lang/source_gen/issues/370
Closes https://github.com/dart-lang/json_serializable/pull/604
Fixes https://github.com/dart-lang/json_serializable/issues/557
=> Add support for an `ignore_for_file` option to `combining_builder`.

source_gen/test/builder_test.dart
A warning is emitted in `build_resolvers`>= 1.3.7 that does not indicate failure.
Handle this case in tests.
See https://github.com/dart-lang/build/commit/aede119300880c268f661fa5b1380b1a3e060bb6
=> Handle new warning from build system

source_gen/lib/builder.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/output_helpers.dart, source_gen/test/builder_test.dart, source_gen/test/output_helpers_test.dart, source_gen/test/src/comment_generator.dart
As of Dart 2.1, Future/Stream have been exported from dart:core.
=> Remove unused dart:async imports.

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
Closes https://github.com/dart-lang/source_gen/issues/481 (or as well as I can close that without major breaking changes).
In the case where we have nothing but GeneratorForAnnotation generators, get the compilation unit for the library and if there are zero top level annotations then bail out early.
=> Optimize annotation generators to not resolve libs with no annotations

source_gen/CHANGELOG.md, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
There is a breaking change coming in `package:build` version `2.0.0` for
classes which override `readAsString` from `AssetReader`. The change is
a positive one since it enforces statically the guarantee of the default
encoding chosen which is currently stated in the doc but not enforced.
Prepare for this breaking change early to allow rolling the packages.
There may still be other breaking changes so it is not yet safe to
extend the dependency constraint.
=> Add encoding default to readAsString override

.github/workflows/dart.yml, example/pubspec.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/type_checker_test.dart, tool/ci.sh
Updates for the breaking change in `package:build`.
- Use `Uri.parse` to convert to a URI, and migrate another call to the
unnamed constructor since the URI is hardcoded and it can be resolved
by hand.
- Override to the unpublished version of `build`.
=> Pass URI to AssetId.resolve

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
- Bump the min version of all deps to the null safe version.
- Drop the `-dev` suffix from the version.
=> Prepare to publish for null safety

source_gen/test/external_only_type_checker_test.dart, source_gen/test/type_checker_test.dart
These are the new tests added for TypeChecker, confirming it works for types not defined in `package:` uris. This behavior is still broken internally (the uris have a special scheme there), so we need to separate them out so they can be easily skipped.
=> separate out external only tests into their own file

source_gen/lib/src/utils.dart, source_gen/test/src/comment_generator.dart
Unfortunately I missed one in the tests last time, found yesterday during global presubmit.
=> Add two more '// ignore' comments for non-nullable LibraryElement.name

source_gen/lib/src/constants/revive.dart, source_gen/test/constants_test.dart
Updating source-gen to use type name instead of class name when generating parameter default values.
=> Update revive.dart to use type name instead of class name

source_gen/test/builder_test.dart
A test meant to ensure that a specific method on `Resolver` hasn't been called used to manually invoke the builder with a custom build step.
As `BuildStep` has recently been marked as `@sealed`, we're now using `runBuilder` with a custom reader and the test resolver.
Closes https://github.com/dart-lang/build/issues/3160
=> Avoid implementing `BuildStep`

source_gen/CHANGELOG.md, source_gen/README.md, source_gen/lib/builder.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/constants/revive.dart, source_gen/lib/src/type_checker.dart, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
This adds support for custom output locations, including outputs in different directories, to the combining builder.
- Make output extensions configurable through builder options. The options are validated to ensure the combining builder is running on Dart files and emits Dart files
- Move the check ensuring we have a `part` statement from the `SharedPartBuilder` to the `CombiningBuilder`. The former can't know the correct output location anymore.
This is related to #272, where the implementation in `build` requires cooperation from builders. Given that most generated files come from shared part generators in practice, this would enable generating to different folders for most users.
=> Configurable outputs for the combining builder

source_gen/CHANGELOG.md, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/generator_for_annotation_test.dart
Remove some individual implementations of `Generator` and
`GeneratorForAnnotation` in tests in favor of a general `_StubGenerator`
implementation which can take a callback for it's behavior. This keeps
the interesting behavior for the test contained within the test.
Move the test for `GeneratorForAnnotation` not resolving libraries which
have no annotated elements into the relevant test suite.
=> Stub test generator behavior within tests

source_gen/CHANGELOG.md, source_gen/lib/src/library.dart, source_gen/pubspec.yaml, source_gen/test/generator_for_annotation_test.dart
Fixes #558
`GeneratorForAnnotation` uses `annotatedWith` which uses `allElements`
to search for annotated elements within a library. When the annotation
was applied on a `library` statement it would appear on the
`LibraryElement` which is not included in `topLevelElements` so the
annotation was ignored.
This is a visible behavior change, but since `allElements` could already
have an arbitrary number and types of elements it's unlikely some
implementation is specifically relying on the _absence_ of any given
element, including the library.
=> Include the library in LibraryReader.allElements

source_gen/CHANGELOG.md, source_gen/README.md, source_gen/lib/builder.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/utils.dart, source_gen/test/builder_test.dart, source_gen/test/utils_test.dart
This adds support for custom output locations, including outputs in different directories, to the PartBuilder.
- Make output extensions configurable through builder options. The options are validated to ensure the PartBuilder is running on Dart files and emits Dart files (re-use existing validatedBuildExtensionsFrom)
This was done previously for the combining builder (https://github.com/dart-lang/source_gen/pull/554). This PR is for PartBuilder.
I've added some tests. All tests are passing. But as I'm not an expert of source_gen code, could you please review carefully this PR, especially :
file: source_gen/lib/src/builder.dart
new line:
`final outputId = buildStep.allowedOutputs.single;`
replacing:
`final outputId = buildStep.inputId.changeExtension(_generatedExtension);`
=> Configurable outputs for the PartBuilder

source_gen/CHANGELOG.md, source_gen/lib/src/type_checker.dart, source_gen/test/type_checker_test.dart
When we attempt to add context for errors relating to an annotation we
made the assumption that the declaration AstNode for the element would
always be an AnnotatedNode, however the class model has an unrelated
`metadata` field on `FormalParameter`.
Expand the checks in the test to validate the source span is found for
the exceptions.
Add tests for the exceptions produced for unresolved annotations on
parameters.
=> Handle source spans on annotated parameters

source_gen/CHANGELOG.md, source_gen/lib/src/utils.dart, source_gen/test/builder_test.dart
The combining part builder checks for the existence of a `part` statement in the source file, ensuring that generated code is included properly.
To do this, it computes the relative path of the configured output and the input asset using the `path` library. However, it uses the platform-specific default path context, even though Dart imports always use an URL-based context. This is not a problem if the input and the output are in the same directory, or if the native system uses a forward slash as a path separator. When using custom build extensions putting generated files in a different directory, this turns out to be a problem on Windows.
This PR ensures a consistent checking mechanism by always using the URL context. Fixes #570.
I'm not sure how to test this properly. Ideally we should …
=> Improve missing part handling on Windows

source_gen/CHANGELOG.md, source_gen/lib/src/constants/revive.dart, source_gen/pubspec.yaml, source_gen/test/constants_test.dart
Fixes https://github.com/dart-lang/source_gen/issues/577
This should also be a faster heuristic; when looking for an object of type Foo, check Foo's static fields first. This was already done for enums; I see no reason to do it for all classes.
=> reviving: Prefer static constant fields on constant object's class

source_gen/CHANGELOG.md, source_gen/lib/src/constants/revive.dart, source_gen/lib/src/library.dart, source_gen/pubspec.yaml
Replaced with `classes`.
https://dart-review.googlesource.com/c/sdk/+/235290
=> Migrate off CompliationUnitElement.types

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/test/src/unformatted_code_generator.dart
Closes https://github.com/dart-lang/source_gen/issues/551
I think this is pretty reasonable, especially since you can override the behavior.
@munificent are there any cases you know about where a fix would break code or all they all super safe?
=> auto-apply dartfmt fixes

source_gen/CHANGELOG.md, source_gen/lib/builder.dart, source_gen/pubspec.yaml
Closes #599
This looks like a bug, but it can't currently surface as a problem
because the character at that location is already guaranteed to be
correct due to the glob pattern.
We cannot shorten the regex to check only the end of the file name
because we need to also disallow names which have extra `.` where there
should be a single part identifier. We could simplify the regex to just
check the right number of characters up to the `.` and count on the glob
for the earlier part, but I think it is more readable with the full
regex.
=> Fix a misleading regex

source_gen/CHANGELOG.md, source_gen/README.md, source_gen/pubspec.yaml
See #598
Call out that the reason to avoid using the same extension as the
combining part builder is to avoid conflicts in packages which use both.
Update examples to use the `:` separator instead of the deprecated `|`
for builder keys.
=> Mention extension conflicts in README

source_gen/CHANGELOG.md, source_gen/lib/src/constants/reader.dart, source_gen/lib/src/constants/revive.dart, source_gen/lib/src/constants/utils.dart, source_gen/lib/src/library.dart, source_gen/lib/src/type_checker.dart, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/constants/utils_test.dart, source_gen/test/constants_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/span_for_element_test.dart, source_gen/test/type_checker_test.dart, source_gen/test/utils_test.dart
Bump min analyzer to `^4.4.0` which introduces some of the new APIs
used.
Switch from `ClassElement` to `InterfaceElement` in a utility method to
match the `element2` return type.
=> Avoid deprecated analyzer APIs

source_gen/CHANGELOG.md, source_gen/lib/src/constants/utils.dart, source_gen/pubspec.yaml
`root.fields` has a runtime type of `Iterable<FieldElementImpl>` which
is not compatible with the value used in the `addAll` call.
Using collection literal syntax to fix the issue
Runtime error:
`type 'ExpandIterable<InterfaceType, FieldElement>' is not a subtype of type 'Iterable<FieldElementImpl>' of 'other'`
=> Fix another type issue, prepare for v1.2.5

source_gen/CHANGELOG.md, source_gen/README.md, source_gen/lib/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
Adds a `preamble` to `CombiningBuilder` as discussed in (#624).
TODO:
Wheter remove or deprecate `ignoreForFile`
Doc update
=> Add preamble to CombiningBuilder

.github/workflows/dart.yml, example_usage/mono_pkg.yaml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/constants/reader.dart, source_gen/lib/src/constants/revive.dart, source_gen/lib/src/constants/utils.dart, source_gen/lib/src/library.dart, source_gen/lib/src/type_checker.dart, source_gen/lib/src/utils.dart, source_gen/mono_pkg.yaml, source_gen/pubspec.yaml, source_gen/test/constants_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/type_checker_test.dart, tool/ci.sh
Bump the analyzer dependency to the latest which includes all the
replacement APIs.
Remove uses of deprecated APIs in favor of their replacements.
=> Update calls to deprecated analyzer APIs

source_gen/CHANGELOG.md, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/utils_test.dart
The `validatedBuildExtensionsFrom()` in `utils.js` currently rejects `build_extensions` configurations that use a list of strings rather than a single string.
This PR adds support for lists of strings.
=> Add support for `build_extensions` configuration of builders producing multiple files

source_gen/lib/src/type_checker.dart, source_gen/test/type_checker_test.dart
"Null check operator used on a null value" errors.
=> Fix issue with `isExactlyType` that resulted in unexpected

source_gen/CHANGELOG.md
Prepares for publishing.
Also reformat the `build_extensions` changelog entry.
=> Add CHANGELOG entry for TypeChecker fix

source_gen/CHANGELOG.md, source_gen/lib/src/library.dart, source_gen/test/generator_for_annotation_test.dart
Closes #662
Allows targeting annotated imports, exports, or part directives with
`GeneratorForAnnotation`.
A pattern established by Mockito is to annotate the import of the file
that will be generated.
=> Include directives in LibraryReader.allElements

.github/workflows/publish.yaml
The auto-publish comment already indicates that the package name prefix
should be used.
=> Use prefixed tags for publish config

source_gen/CHANGELOG.md, source_gen/lib/src/type_checker.dart, source_gen/pubspec.yaml
Prepares for landing https://dart-review.googlesource.com/c/sdk/+/300181
I had to make this check in cl/529250286, so I guess there is a type without an element that gets passed, most probably the newly added `InvalidType`. Anyway, the code was unsafe.
=> Prepare for adding InvalidType, make 'TypeChecker.isAssignableFromType()' null safe.

source_gen/CHANGELOG.md, source_gen/lib/src/generator.dart, source_gen/lib/src/span_for_element.dart, source_gen/pubspec.yaml, source_gen/test/span_for_element_test.dart
Allow attempting to find the source location from an AstNode as an
alternative to finding it from an Element.
=> Add a `node` to `InvalidGenerationSourceError`

source_gen/lib/src/library.dart
Avoid moving a runtime null check to a static null check because some
code locations may be passing a nullable reference which is never null.
=> Restore a dynamic argument

source_gen/test/output_helpers_test.dart
This is a weird one, so I'm going to try to carefully explain the situation and my steps. Here is the code in question:
```dart
void _testSimpleValue(String testName, Object? value, Object? expected) {
// ...
_testFunction('Future<$testName>', Future.value(value), expected);
// -------------------------------------^ inferred type argument
// ...
}
void _testFunction(String testName, Object? value, Object? expected) { /* ... */ }
```
This code works today. It appears that the type of `Future.value(...)` inferred by CFE is `Future<Object?>`. A `Future<Object?>` constructed with the `value` constructor, and an `Object?` argument is sound. However, in https://github.com/dart-lang/language/issues/3304, it was decided that CFE infers the wrong type here, and should infer `Future<Object>`.
If …
=> Use type argument for Future of nullable value in test

source_gen/CHANGELOG.md, source_gen/lib/src/generator_for_annotation.dart, source_gen/pubspec.yaml, source_gen/test/generator_for_annotation_test.dart
Closes https://github.com/dart-lang/source_gen/issues/682
This only enables configuration right now, mostly to avoid any change in default behavior. I am open to changing the default too though.
=> Add configuration for not throwing on unresolved annotations

source_gen/CHANGELOG.md, source_gen/lib/source_gen.dart, source_gen/lib/src/generator.dart, source_gen/pubspec.yaml
See https://github.com/dart-lang/build/issues/3585
Rename to `InvalidGenerationSource` and change to a subtype of
`Exception`. This class is not thrown to indicate a programming error in
the code that is running, it is thrown to indicate an error in the code
under analysis. It was originally implemented without a super type and
the name ending in "Error" was not specifically discussed, but it was
intended to convey an "error in build input", not an error in the
builder implementation (where it is thrown). Later a lint required it to
be a subtype of either `Error` or `Exception`, and the `Error` supertype
was chosen without discussion because of the name, even though it's not
thrown as an `Error` in the sense where that distinction matters.
Add a type alias for the exception with the old …
=> Make InvalidGenerationSourceError an Exception

source_gen/CHANGELOG.md, source_gen/lib/src/generator_for_annotation.dart, source_gen/pubspec.yaml
Closes #648
Expand the doc about the return type to explain that when there are
multiple output strings they are deduplicated, allowing each annotated
element to output content that they may need to share with other
elements.
=> Document generateForAnnotatedElement deduplication

source_gen/CHANGELOG.md, source_gen/pubspec.yaml, source_gen/test/library/path_to_url_test.dart
Preparation for https://dart-review.googlesource.com/c/sdk/+/369560
---
=> Import package:analyzer/source/source.dart instead of internal.

source_gen/CHANGELOG.md, source_gen/lib/src/constants/revive.dart, source_gen/test/constants_test.dart
Variables have been tracked on DartObject since https://dart.googlesource.com/sdk/+/54b7f4b72a1701f8f9a0334c94ce6f59732bd261. This change uses the variable in the reviver if it exists. I believe the existing tests in https://github.com/dart-lang/source_gen/blob/master/source_gen/test/constants_test.dart already cover this, but lmk if you'd like any additional tests
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be …
=> Revive to the object's `variableElement` if available

source_gen/CHANGELOG.md, source_gen/lib/src/constants/revive.dart, source_gen/test/constants_test.dart
This reverts commit ac1837fdd1ba6eed236082c88537fdb8c619b1f4, due to it breaking mockito.
=> Revert "Revive to the object's `variableElement` if available (#713)"

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart
Related: https://github.com/dart-lang/source_gen/issues/706.
This PR adds an optional `bool? writesDescriptions` field to the `_Builder` base class constructor.
By default, it is `true`, but if explicitly set to `false`, the generated description comments will not be included
in the generated output.
See related link for my use-case. This will be useful so that _any_ file can be generated with this tool for Dart.
Checklist
---
=> `feature:` Optionally omit generated description comments in output

.github/workflows/dart.yml, example_usage/pubspec.yaml, source_gen/CHANGELOG.md, source_gen/lib/src/constants/revive.dart, source_gen/pubspec.yaml
Prepare for https://dart-review.googlesource.com/c/sdk/+/385100
=> Require analyzer ^6.9.0, switch to using 'enclosingElement3'.

example_usage/lib/library_source.g.dart, example_usage/lib/library_source.info.dart, source_gen/CHANGELOG.md, source_gen/lib/builder.dart, source_gen/lib/src/builder.dart, source_gen/test/builder_test.dart, source_gen/test/generator_for_annotation_test.dart
Closes #724
The 3 places where a Dart unit can be output are as a `LibraryBuildr`,
as a `PartBuilder`, or as a combined part. `SharedPartBuilder` output
does not need the width comment. Add a constant for the comment and use
it while writing each of the 3 types of output.
=> Add dart format width comments

source_gen/lib/src/library.dart
The direct read of parts from the library element is deprecated.
Retain ignores for reading imports and exports since they
will be restored without a deprecation.
Unblocks https://dart-review.googlesource.com/c/sdk/+/388643
=> Read parts with the defining compilation unit

source_gen/lib/src/library.dart
Follow up for https://github.com/dart-lang/source_gen/pull/728
=> Read libraryImports/libraryExports from the defining unit.

analysis_options.yaml, example/lib/src/member_count_library_generator.dart, example/lib/src/multiplier_generator.dart, example/lib/src/property_product_generator.dart, example/lib/src/property_sum_generator.dart, example/lib/src/utils.dart, source_gen/lib/source_gen.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/generator.dart, source_gen/lib/src/generator_for_annotation.dart, source_gen/lib/src/library.dart, source_gen/lib/src/span_for_element.dart, source_gen/lib/src/type_checker.dart, source_gen/pubspec.yaml, source_gen/test/external_only_type_checker_test.dart, source_gen/test/generator_for_annotation_test.dart, source_gen/test/library/find_type_test.dart, source_gen/test/library/path_to_url_test.dart, source_gen/test/type_checker_test.dart
See https://docs.google.com/presentation/d/1Vxr-y5ljuo0Os78R4tKZg8cc0In984EQcLs06HOqS28/edit#slide=id.p for the new element model details. It is possible that you will not able access it, unless you work for Google.
=> Add APIs to expose analyzer elements2 models.

example/lib/src/multiplier_generator.dart, source_gen/lib/builder.dart, source_gen/lib/source_gen.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/constants/utils.dart, source_gen/lib/src/generator.dart, source_gen/lib/src/generator_for_annotation.dart, source_gen/lib/src/library.dart, source_gen/lib/src/span_for_element.dart, source_gen/lib/src/type_checker.dart, source_gen/lib/src/utils.dart, source_gen/test/constants/utils_test.dart, source_gen/test/constants_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/library/find_type_test.dart, source_gen/test/span_for_element_test.dart, source_gen/test/src/comment_generator.dart, source_gen/test/type_checker_test.dart, source_gen/test/utils_test.dart
This should now be the releasable state for source_gen.
=> Remove deprecated methods

source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/generator_for_annotation_test.dart
Previously we would bail out early for files with no top level annotations, this also skips well known annotations (although it isn't perfect, and assumes people aren't shadowing these names).
=> skip files with only known annotation names

source_gen/CHANGELOG.md, source_gen/pubspec.yaml
=> Release 3.0.0.

example/lib/src/multiplier_generator.dart, source_gen/CHANGELOG.md
=> Mention directive annotations in CHANGELOG and example.

source_gen/CHANGELOG.md, source_gen/lib/src/generator.dart, source_gen/lib/src/span_for_element.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/src/comment_generator.dart
=> Support fragments in InvalidGenerationSource.

example_usage/lib/library_source.info.dart, source_gen/CHANGELOG.md, source_gen/lib/src/builder.dart, source_gen/pubspec.yaml, source_gen/test/builder_test.dart, source_gen/test/generator_for_annotation_test.dart
Let linquist continue to find the generated file marker on the first
line, the dart format width comment is allowed to be on any line.
Look for the generated file line exactly and when it starts the file
insert the dart format comment following it.
=> Keep generated file comments on the first line

example/lib/src/multiplier_generator.dart, example/lib/src/property_product_generator.dart, example/lib/src/property_sum_generator.dart, example/lib/src/utils.dart, source_gen/lib/src/builder.dart, source_gen/lib/src/constants/reader.dart, source_gen/lib/src/constants/revive.dart, source_gen/lib/src/constants/utils.dart, source_gen/lib/src/generator.dart, source_gen/lib/src/generator_for_annotation.dart, source_gen/lib/src/library.dart, source_gen/lib/src/span_for_element.dart, source_gen/lib/src/type_checker.dart, source_gen/lib/src/utils.dart, source_gen/pubspec.yaml, source_gen/test/constants/utils_test.dart, source_gen/test/constants_test.dart, source_gen/test/external_only_type_checker_test.dart, source_gen/test/generator_for_annotation_test.dart, source_gen/test/library/find_type_test.dart, source_gen/test/library/path_to_url_test.dart, source_gen/test/span_for_element_test.dart, source_gen/test/src/comment_generator.dart, source_gen/test/type_checker_test.dart, source_gen/test/utils_test.dart
Also deleted
```dart
if (element case final Annotatable annotatable) {
final annotations = annotatable.metadata2.annotations;
if (annotations.isEmpty) {
return null;
}
}
```
from `source_gen/lib/src/type_checker.dart` because it repeated a check that was done a few lines later.
=> Bring up to analyzer 8.1.1, get rid of deprecated classes and methods.
